namespace Cafe_Management
{
    partial class frmUserOrder
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmUserOrder));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnPlaceOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.lblYourOrder = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnAddToCart = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblOrdAmount = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtSellerName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtOrderNum = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgvItems = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.cmbCategory = new System.Windows.Forms.ComboBox();
            this.lblPlacOrder = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnClose = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuFormDrag1 = new Bunifu.UI.WinForms.BunifuFormDrag();
            this.panel2 = new System.Windows.Forms.Panel();
            this.btnUsers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnItems = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lnkLogout = new System.Windows.Forms.LinkLabel();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvItems)).BeginInit();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.bunifuTextBox1);
            this.panel1.Controls.Add(this.btnPlaceOrder);
            this.panel1.Controls.Add(this.bunifuDataGridView1);
            this.panel1.Controls.Add(this.lblYourOrder);
            this.panel1.Controls.Add(this.btnAddToCart);
            this.panel1.Controls.Add(this.lblOrdAmount);
            this.panel1.Controls.Add(this.txtSellerName);
            this.panel1.Controls.Add(this.txtOrderNum);
            this.panel1.Controls.Add(this.dgvItems);
            this.panel1.Controls.Add(this.cmbCategory);
            this.panel1.Controls.Add(this.lblPlacOrder);
            this.panel1.Location = new System.Drawing.Point(165, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(741, 513);
            this.panel1.TabIndex = 0;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.White;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(43, 200);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties4;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "Quantity";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(145, 39);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBox1.TabIndex = 10;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "Quantity";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // btnPlaceOrder
            // 
            this.btnPlaceOrder.AllowAnimations = true;
            this.btnPlaceOrder.AllowMouseEffects = true;
            this.btnPlaceOrder.AllowToggling = false;
            this.btnPlaceOrder.AnimationSpeed = 200;
            this.btnPlaceOrder.AutoGenerateColors = false;
            this.btnPlaceOrder.AutoRoundBorders = false;
            this.btnPlaceOrder.AutoSizeLeftIcon = true;
            this.btnPlaceOrder.AutoSizeRightIcon = true;
            this.btnPlaceOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnPlaceOrder.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnPlaceOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPlaceOrder.BackgroundImage")));
            this.btnPlaceOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaceOrder.ButtonText = "Place Order";
            this.btnPlaceOrder.ButtonTextMarginLeft = 0;
            this.btnPlaceOrder.ColorContrastOnClick = 45;
            this.btnPlaceOrder.ColorContrastOnHover = 45;
            this.btnPlaceOrder.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnPlaceOrder.CustomizableEdges = borderEdges1;
            this.btnPlaceOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPlaceOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPlaceOrder.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnPlaceOrder.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnPlaceOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPlaceOrder.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPlaceOrder.ForeColor = System.Drawing.Color.White;
            this.btnPlaceOrder.IconLeft = null;
            this.btnPlaceOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPlaceOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPlaceOrder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPlaceOrder.IconMarginLeft = 11;
            this.btnPlaceOrder.IconPadding = 10;
            this.btnPlaceOrder.IconRight = null;
            this.btnPlaceOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPlaceOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPlaceOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPlaceOrder.IconSize = 25;
            this.btnPlaceOrder.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnPlaceOrder.IdleBorderRadius = 0;
            this.btnPlaceOrder.IdleBorderThickness = 0;
            this.btnPlaceOrder.IdleFillColor = System.Drawing.Color.Empty;
            this.btnPlaceOrder.IdleIconLeftImage = null;
            this.btnPlaceOrder.IdleIconRightImage = null;
            this.btnPlaceOrder.IndicateFocus = false;
            this.btnPlaceOrder.Location = new System.Drawing.Point(376, 463);
            this.btnPlaceOrder.Name = "btnPlaceOrder";
            this.btnPlaceOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPlaceOrder.OnDisabledState.BorderRadius = 1;
            this.btnPlaceOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaceOrder.OnDisabledState.BorderThickness = 1;
            this.btnPlaceOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPlaceOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPlaceOrder.OnDisabledState.IconLeftImage = null;
            this.btnPlaceOrder.OnDisabledState.IconRightImage = null;
            this.btnPlaceOrder.onHoverState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.onHoverState.BorderRadius = 1;
            this.btnPlaceOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaceOrder.onHoverState.BorderThickness = 1;
            this.btnPlaceOrder.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnPlaceOrder.onHoverState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.onHoverState.IconLeftImage = null;
            this.btnPlaceOrder.onHoverState.IconRightImage = null;
            this.btnPlaceOrder.OnIdleState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.OnIdleState.BorderRadius = 1;
            this.btnPlaceOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaceOrder.OnIdleState.BorderThickness = 1;
            this.btnPlaceOrder.OnIdleState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPlaceOrder.OnIdleState.IconLeftImage = null;
            this.btnPlaceOrder.OnIdleState.IconRightImage = null;
            this.btnPlaceOrder.OnPressedState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.OnPressedState.BorderRadius = 1;
            this.btnPlaceOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaceOrder.OnPressedState.BorderThickness = 1;
            this.btnPlaceOrder.OnPressedState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnPlaceOrder.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPlaceOrder.OnPressedState.IconLeftImage = null;
            this.btnPlaceOrder.OnPressedState.IconRightImage = null;
            this.btnPlaceOrder.Size = new System.Drawing.Size(145, 33);
            this.btnPlaceOrder.TabIndex = 9;
            this.btnPlaceOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPlaceOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPlaceOrder.TextMarginLeft = 0;
            this.btnPlaceOrder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPlaceOrder.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(241, 270);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(480, 175);
            this.bunifuDataGridView1.TabIndex = 8;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // lblYourOrder
            // 
            this.lblYourOrder.AllowParentOverrides = false;
            this.lblYourOrder.AutoEllipsis = false;
            this.lblYourOrder.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblYourOrder.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblYourOrder.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblYourOrder.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.lblYourOrder.Location = new System.Drawing.Point(412, 234);
            this.lblYourOrder.Name = "lblYourOrder";
            this.lblYourOrder.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblYourOrder.Size = new System.Drawing.Size(109, 30);
            this.lblYourOrder.TabIndex = 7;
            this.lblYourOrder.Text = "Your Order";
            this.lblYourOrder.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblYourOrder.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnAddToCart
            // 
            this.btnAddToCart.AllowAnimations = true;
            this.btnAddToCart.AllowMouseEffects = true;
            this.btnAddToCart.AllowToggling = false;
            this.btnAddToCart.AnimationSpeed = 200;
            this.btnAddToCart.AutoGenerateColors = false;
            this.btnAddToCart.AutoRoundBorders = false;
            this.btnAddToCart.AutoSizeLeftIcon = true;
            this.btnAddToCart.AutoSizeRightIcon = true;
            this.btnAddToCart.BackColor = System.Drawing.Color.Transparent;
            this.btnAddToCart.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAddToCart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.BackgroundImage")));
            this.btnAddToCart.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.ButtonText = "Add To Cart";
            this.btnAddToCart.ButtonTextMarginLeft = 0;
            this.btnAddToCart.ColorContrastOnClick = 45;
            this.btnAddToCart.ColorContrastOnHover = 45;
            this.btnAddToCart.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAddToCart.CustomizableEdges = borderEdges2;
            this.btnAddToCart.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddToCart.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddToCart.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddToCart.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddToCart.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddToCart.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddToCart.ForeColor = System.Drawing.Color.White;
            this.btnAddToCart.IconLeft = null;
            this.btnAddToCart.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddToCart.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddToCart.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddToCart.IconMarginLeft = 11;
            this.btnAddToCart.IconPadding = 10;
            this.btnAddToCart.IconRight = null;
            this.btnAddToCart.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddToCart.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddToCart.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddToCart.IconSize = 25;
            this.btnAddToCart.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAddToCart.IdleBorderRadius = 0;
            this.btnAddToCart.IdleBorderThickness = 0;
            this.btnAddToCart.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAddToCart.IdleIconLeftImage = null;
            this.btnAddToCart.IdleIconRightImage = null;
            this.btnAddToCart.IndicateFocus = false;
            this.btnAddToCart.Location = new System.Drawing.Point(43, 261);
            this.btnAddToCart.Name = "btnAddToCart";
            this.btnAddToCart.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddToCart.OnDisabledState.BorderRadius = 1;
            this.btnAddToCart.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnDisabledState.BorderThickness = 1;
            this.btnAddToCart.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddToCart.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddToCart.OnDisabledState.IconLeftImage = null;
            this.btnAddToCart.OnDisabledState.IconRightImage = null;
            this.btnAddToCart.onHoverState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.onHoverState.BorderRadius = 1;
            this.btnAddToCart.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.onHoverState.BorderThickness = 1;
            this.btnAddToCart.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnAddToCart.onHoverState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.onHoverState.IconLeftImage = null;
            this.btnAddToCart.onHoverState.IconRightImage = null;
            this.btnAddToCart.OnIdleState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.OnIdleState.BorderRadius = 1;
            this.btnAddToCart.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnIdleState.BorderThickness = 1;
            this.btnAddToCart.OnIdleState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddToCart.OnIdleState.IconLeftImage = null;
            this.btnAddToCart.OnIdleState.IconRightImage = null;
            this.btnAddToCart.OnPressedState.BorderColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.OnPressedState.BorderRadius = 1;
            this.btnAddToCart.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnPressedState.BorderThickness = 1;
            this.btnAddToCart.OnPressedState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnAddToCart.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddToCart.OnPressedState.IconLeftImage = null;
            this.btnAddToCart.OnPressedState.IconRightImage = null;
            this.btnAddToCart.Size = new System.Drawing.Size(145, 33);
            this.btnAddToCart.TabIndex = 5;
            this.btnAddToCart.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddToCart.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddToCart.TextMarginLeft = 0;
            this.btnAddToCart.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddToCart.UseDefaultRadiusAndThickness = true;
            // 
            // lblOrdAmount
            // 
            this.lblOrdAmount.AllowParentOverrides = false;
            this.lblOrdAmount.AutoEllipsis = false;
            this.lblOrdAmount.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblOrdAmount.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblOrdAmount.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOrdAmount.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.lblOrdAmount.Location = new System.Drawing.Point(578, 464);
            this.lblOrdAmount.Name = "lblOrdAmount";
            this.lblOrdAmount.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblOrdAmount.Size = new System.Drawing.Size(143, 30);
            this.lblOrdAmount.TabIndex = 6;
            this.lblOrdAmount.Text = "Order Amount";
            this.lblOrdAmount.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblOrdAmount.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtSellerName
            // 
            this.txtSellerName.AcceptsReturn = false;
            this.txtSellerName.AcceptsTab = false;
            this.txtSellerName.AnimationSpeed = 200;
            this.txtSellerName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSellerName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSellerName.AutoSizeHeight = true;
            this.txtSellerName.BackColor = System.Drawing.Color.White;
            this.txtSellerName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSellerName.BackgroundImage")));
            this.txtSellerName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSellerName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSellerName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSellerName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSellerName.BorderRadius = 1;
            this.txtSellerName.BorderThickness = 1;
            this.txtSellerName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSellerName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSellerName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSellerName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSellerName.DefaultText = "";
            this.txtSellerName.FillColor = System.Drawing.Color.White;
            this.txtSellerName.HideSelection = true;
            this.txtSellerName.IconLeft = null;
            this.txtSellerName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSellerName.IconPadding = 10;
            this.txtSellerName.IconRight = null;
            this.txtSellerName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSellerName.Lines = new string[0];
            this.txtSellerName.Location = new System.Drawing.Point(43, 155);
            this.txtSellerName.MaxLength = 32767;
            this.txtSellerName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSellerName.Modified = false;
            this.txtSellerName.Multiline = false;
            this.txtSellerName.Name = "txtSellerName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSellerName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSellerName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSellerName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSellerName.OnIdleState = stateProperties8;
            this.txtSellerName.Padding = new System.Windows.Forms.Padding(3);
            this.txtSellerName.PasswordChar = '\0';
            this.txtSellerName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSellerName.PlaceholderText = "SellerName";
            this.txtSellerName.ReadOnly = false;
            this.txtSellerName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSellerName.SelectedText = "";
            this.txtSellerName.SelectionLength = 0;
            this.txtSellerName.SelectionStart = 0;
            this.txtSellerName.ShortcutsEnabled = true;
            this.txtSellerName.Size = new System.Drawing.Size(145, 39);
            this.txtSellerName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtSellerName.TabIndex = 5;
            this.txtSellerName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSellerName.TextMarginBottom = 0;
            this.txtSellerName.TextMarginLeft = 3;
            this.txtSellerName.TextMarginTop = 1;
            this.txtSellerName.TextPlaceholder = "SellerName";
            this.txtSellerName.UseSystemPasswordChar = false;
            this.txtSellerName.WordWrap = true;
            // 
            // txtOrderNum
            // 
            this.txtOrderNum.AcceptsReturn = false;
            this.txtOrderNum.AcceptsTab = false;
            this.txtOrderNum.AnimationSpeed = 200;
            this.txtOrderNum.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOrderNum.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOrderNum.AutoSizeHeight = true;
            this.txtOrderNum.BackColor = System.Drawing.Color.White;
            this.txtOrderNum.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOrderNum.BackgroundImage")));
            this.txtOrderNum.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtOrderNum.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtOrderNum.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtOrderNum.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtOrderNum.BorderRadius = 1;
            this.txtOrderNum.BorderThickness = 1;
            this.txtOrderNum.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtOrderNum.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOrderNum.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderNum.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtOrderNum.DefaultText = "";
            this.txtOrderNum.FillColor = System.Drawing.Color.White;
            this.txtOrderNum.HideSelection = true;
            this.txtOrderNum.IconLeft = null;
            this.txtOrderNum.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderNum.IconPadding = 10;
            this.txtOrderNum.IconRight = null;
            this.txtOrderNum.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderNum.Lines = new string[0];
            this.txtOrderNum.Location = new System.Drawing.Point(43, 110);
            this.txtOrderNum.MaxLength = 32767;
            this.txtOrderNum.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOrderNum.Modified = false;
            this.txtOrderNum.Multiline = false;
            this.txtOrderNum.Name = "txtOrderNum";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderNum.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtOrderNum.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderNum.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderNum.OnIdleState = stateProperties12;
            this.txtOrderNum.Padding = new System.Windows.Forms.Padding(3);
            this.txtOrderNum.PasswordChar = '\0';
            this.txtOrderNum.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOrderNum.PlaceholderText = "OrderNum";
            this.txtOrderNum.ReadOnly = false;
            this.txtOrderNum.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOrderNum.SelectedText = "";
            this.txtOrderNum.SelectionLength = 0;
            this.txtOrderNum.SelectionStart = 0;
            this.txtOrderNum.ShortcutsEnabled = true;
            this.txtOrderNum.Size = new System.Drawing.Size(145, 39);
            this.txtOrderNum.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtOrderNum.TabIndex = 4;
            this.txtOrderNum.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOrderNum.TextMarginBottom = 0;
            this.txtOrderNum.TextMarginLeft = 3;
            this.txtOrderNum.TextMarginTop = 1;
            this.txtOrderNum.TextPlaceholder = "OrderNum";
            this.txtOrderNum.UseSystemPasswordChar = false;
            this.txtOrderNum.WordWrap = true;
            // 
            // dgvItems
            // 
            this.dgvItems.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dgvItems.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvItems.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvItems.BackgroundColor = System.Drawing.Color.White;
            this.dgvItems.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvItems.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvItems.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvItems.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dgvItems.ColumnHeadersHeight = 40;
            this.dgvItems.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvItems.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvItems.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvItems.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvItems.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvItems.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvItems.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvItems.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvItems.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvItems.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvItems.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvItems.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvItems.CurrentTheme.Name = null;
            this.dgvItems.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvItems.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvItems.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvItems.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvItems.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvItems.DefaultCellStyle = dataGridViewCellStyle6;
            this.dgvItems.EnableHeadersVisualStyles = false;
            this.dgvItems.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvItems.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvItems.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvItems.HeaderForeColor = System.Drawing.Color.White;
            this.dgvItems.Location = new System.Drawing.Point(206, 72);
            this.dgvItems.Name = "dgvItems";
            this.dgvItems.RowHeadersVisible = false;
            this.dgvItems.RowTemplate.Height = 40;
            this.dgvItems.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvItems.Size = new System.Drawing.Size(457, 134);
            this.dgvItems.TabIndex = 3;
            this.dgvItems.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // cmbCategory
            // 
            this.cmbCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategory.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCategory.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.cmbCategory.FormattingEnabled = true;
            this.cmbCategory.Items.AddRange(new object[] {
            "Food",
            "Beverage"});
            this.cmbCategory.Location = new System.Drawing.Point(43, 72);
            this.cmbCategory.Name = "cmbCategory";
            this.cmbCategory.Size = new System.Drawing.Size(157, 32);
            this.cmbCategory.TabIndex = 2;
            // 
            // lblPlacOrder
            // 
            this.lblPlacOrder.AllowParentOverrides = false;
            this.lblPlacOrder.AutoEllipsis = false;
            this.lblPlacOrder.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPlacOrder.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPlacOrder.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPlacOrder.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.lblPlacOrder.Location = new System.Drawing.Point(317, 18);
            this.lblPlacOrder.Name = "lblPlacOrder";
            this.lblPlacOrder.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPlacOrder.Size = new System.Drawing.Size(113, 30);
            this.lblPlacOrder.TabIndex = 1;
            this.lblPlacOrder.Text = "Place Order";
            this.lblPlacOrder.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPlacOrder.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnClose
            // 
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClose.BunifuFormDrag = null;
            this.btnClose.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.CloseBoxOptions.BorderRadius = 0;
            this.btnClose.CloseBoxOptions.Enabled = true;
            this.btnClose.CloseBoxOptions.EnableDefaultAction = true;
            this.btnClose.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.btnClose.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("btnClose.CloseBoxOptions.Icon")));
            this.btnClose.CloseBoxOptions.IconAlt = null;
            this.btnClose.CloseBoxOptions.IconColor = System.Drawing.Color.White;
            this.btnClose.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.btnClose.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.btnClose.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.btnClose.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.HelpBox = false;
            this.btnClose.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.HelpBoxOptions.BorderRadius = 0;
            this.btnClose.HelpBoxOptions.Enabled = true;
            this.btnClose.HelpBoxOptions.EnableDefaultAction = true;
            this.btnClose.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.btnClose.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("btnClose.HelpBoxOptions.Icon")));
            this.btnClose.HelpBoxOptions.IconAlt = null;
            this.btnClose.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.btnClose.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.btnClose.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.btnClose.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.btnClose.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.btnClose.Location = new System.Drawing.Point(865, 1);
            this.btnClose.MaximizeBox = false;
            this.btnClose.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.MaximizeBoxOptions.BorderRadius = 0;
            this.btnClose.MaximizeBoxOptions.Enabled = true;
            this.btnClose.MaximizeBoxOptions.EnableDefaultAction = true;
            this.btnClose.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.btnClose.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("btnClose.MaximizeBoxOptions.Icon")));
            this.btnClose.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("btnClose.MaximizeBoxOptions.IconAlt")));
            this.btnClose.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.btnClose.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.btnClose.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.btnClose.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.btnClose.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.btnClose.MinimizeBox = false;
            this.btnClose.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.MinimizeBoxOptions.BorderRadius = 0;
            this.btnClose.MinimizeBoxOptions.Enabled = true;
            this.btnClose.MinimizeBoxOptions.EnableDefaultAction = true;
            this.btnClose.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.btnClose.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("btnClose.MinimizeBoxOptions.Icon")));
            this.btnClose.MinimizeBoxOptions.IconAlt = null;
            this.btnClose.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.btnClose.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.btnClose.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.btnClose.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.btnClose.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.btnClose.Name = "btnClose";
            this.btnClose.ShowDesignBorders = false;
            this.btnClose.Size = new System.Drawing.Size(51, 51);
            this.btnClose.TabIndex = 3;
            // 
            // bunifuFormDrag1
            // 
            this.bunifuFormDrag1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDrag1.ContainerControl = this;
            this.bunifuFormDrag1.DockIndicatorsOpacity = 0.5D;
            this.bunifuFormDrag1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDrag1.DockingOptions.DockAll = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDrag1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDrag1.DockingOptions.DockLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockRight = true;
            this.bunifuFormDrag1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockTopRight = true;
            this.bunifuFormDrag1.DragOpacity = 0.9D;
            this.bunifuFormDrag1.Enabled = true;
            this.bunifuFormDrag1.ParentForm = this;
            this.bunifuFormDrag1.ShowCursorChanges = true;
            this.bunifuFormDrag1.ShowDockingIndicators = true;
            this.bunifuFormDrag1.TitleBarOptions.BunifuFormDrag = this.bunifuFormDrag1;
            this.bunifuFormDrag1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDrag1.TitleBarOptions.Enabled = true;
            this.bunifuFormDrag1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDrag1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.btnUsers);
            this.panel2.Controls.Add(this.btnItems);
            this.panel2.Controls.Add(this.lnkLogout);
            this.panel2.Controls.Add(this.panel1);
            this.panel2.Location = new System.Drawing.Point(0, 55);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(918, 529);
            this.panel2.TabIndex = 4;
            // 
            // btnUsers
            // 
            this.btnUsers.AllowAnimations = true;
            this.btnUsers.AllowMouseEffects = true;
            this.btnUsers.AllowToggling = false;
            this.btnUsers.AnimationSpeed = 200;
            this.btnUsers.AutoGenerateColors = false;
            this.btnUsers.AutoRoundBorders = false;
            this.btnUsers.AutoSizeLeftIcon = true;
            this.btnUsers.AutoSizeRightIcon = true;
            this.btnUsers.BackColor = System.Drawing.Color.Transparent;
            this.btnUsers.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUsers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUsers.BackgroundImage")));
            this.btnUsers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.ButtonText = "Users";
            this.btnUsers.ButtonTextMarginLeft = 0;
            this.btnUsers.ColorContrastOnClick = 45;
            this.btnUsers.ColorContrastOnHover = 45;
            this.btnUsers.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnUsers.CustomizableEdges = borderEdges3;
            this.btnUsers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUsers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsers.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUsers.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUsers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUsers.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsers.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnUsers.IconLeft = null;
            this.btnUsers.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsers.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUsers.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUsers.IconMarginLeft = 11;
            this.btnUsers.IconPadding = 10;
            this.btnUsers.IconRight = null;
            this.btnUsers.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsers.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUsers.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUsers.IconSize = 25;
            this.btnUsers.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUsers.IdleBorderRadius = 0;
            this.btnUsers.IdleBorderThickness = 0;
            this.btnUsers.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUsers.IdleIconLeftImage = null;
            this.btnUsers.IdleIconRightImage = null;
            this.btnUsers.IndicateFocus = false;
            this.btnUsers.Location = new System.Drawing.Point(9, 89);
            this.btnUsers.Name = "btnUsers";
            this.btnUsers.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsers.OnDisabledState.BorderRadius = 1;
            this.btnUsers.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnDisabledState.BorderThickness = 1;
            this.btnUsers.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsers.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsers.OnDisabledState.IconLeftImage = null;
            this.btnUsers.OnDisabledState.IconRightImage = null;
            this.btnUsers.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.onHoverState.BorderRadius = 1;
            this.btnUsers.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.onHoverState.BorderThickness = 1;
            this.btnUsers.onHoverState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnUsers.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUsers.onHoverState.IconLeftImage = null;
            this.btnUsers.onHoverState.IconRightImage = null;
            this.btnUsers.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.OnIdleState.BorderRadius = 1;
            this.btnUsers.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnIdleState.BorderThickness = 1;
            this.btnUsers.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnUsers.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnUsers.OnIdleState.IconLeftImage = null;
            this.btnUsers.OnIdleState.IconRightImage = null;
            this.btnUsers.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.OnPressedState.BorderRadius = 1;
            this.btnUsers.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnPressedState.BorderThickness = 1;
            this.btnUsers.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnUsers.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnUsers.OnPressedState.IconLeftImage = null;
            this.btnUsers.OnPressedState.IconRightImage = null;
            this.btnUsers.Size = new System.Drawing.Size(150, 39);
            this.btnUsers.TabIndex = 7;
            this.btnUsers.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUsers.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUsers.TextMarginLeft = 0;
            this.btnUsers.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUsers.UseDefaultRadiusAndThickness = true;
            // 
            // btnItems
            // 
            this.btnItems.AllowAnimations = true;
            this.btnItems.AllowMouseEffects = true;
            this.btnItems.AllowToggling = false;
            this.btnItems.AnimationSpeed = 200;
            this.btnItems.AutoGenerateColors = false;
            this.btnItems.AutoRoundBorders = false;
            this.btnItems.AutoSizeLeftIcon = true;
            this.btnItems.AutoSizeRightIcon = true;
            this.btnItems.BackColor = System.Drawing.Color.Transparent;
            this.btnItems.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnItems.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnItems.BackgroundImage")));
            this.btnItems.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.ButtonText = "Items";
            this.btnItems.ButtonTextMarginLeft = 0;
            this.btnItems.ColorContrastOnClick = 45;
            this.btnItems.ColorContrastOnHover = 45;
            this.btnItems.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnItems.CustomizableEdges = borderEdges4;
            this.btnItems.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnItems.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnItems.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnItems.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnItems.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnItems.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnItems.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnItems.IconLeft = null;
            this.btnItems.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnItems.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnItems.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnItems.IconMarginLeft = 11;
            this.btnItems.IconPadding = 10;
            this.btnItems.IconRight = null;
            this.btnItems.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnItems.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnItems.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnItems.IconSize = 25;
            this.btnItems.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnItems.IdleBorderRadius = 0;
            this.btnItems.IdleBorderThickness = 0;
            this.btnItems.IdleFillColor = System.Drawing.Color.Empty;
            this.btnItems.IdleIconLeftImage = null;
            this.btnItems.IdleIconRightImage = null;
            this.btnItems.IndicateFocus = false;
            this.btnItems.Location = new System.Drawing.Point(9, 44);
            this.btnItems.Name = "btnItems";
            this.btnItems.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnItems.OnDisabledState.BorderRadius = 1;
            this.btnItems.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnDisabledState.BorderThickness = 1;
            this.btnItems.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnItems.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnItems.OnDisabledState.IconLeftImage = null;
            this.btnItems.OnDisabledState.IconRightImage = null;
            this.btnItems.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnItems.onHoverState.BorderRadius = 1;
            this.btnItems.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.onHoverState.BorderThickness = 1;
            this.btnItems.onHoverState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.btnItems.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnItems.onHoverState.IconLeftImage = null;
            this.btnItems.onHoverState.IconRightImage = null;
            this.btnItems.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnItems.OnIdleState.BorderRadius = 1;
            this.btnItems.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnIdleState.BorderThickness = 1;
            this.btnItems.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnItems.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnItems.OnIdleState.IconLeftImage = null;
            this.btnItems.OnIdleState.IconRightImage = null;
            this.btnItems.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnItems.OnPressedState.BorderRadius = 1;
            this.btnItems.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnPressedState.BorderThickness = 1;
            this.btnItems.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnItems.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateBlue;
            this.btnItems.OnPressedState.IconLeftImage = null;
            this.btnItems.OnPressedState.IconRightImage = null;
            this.btnItems.Size = new System.Drawing.Size(150, 39);
            this.btnItems.TabIndex = 6;
            this.btnItems.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnItems.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnItems.TextMarginLeft = 0;
            this.btnItems.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnItems.UseDefaultRadiusAndThickness = true;
            this.btnItems.Click += new System.EventHandler(this.btnItems_Click);
            // 
            // lnkLogout
            // 
            this.lnkLogout.AutoSize = true;
            this.lnkLogout.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lnkLogout.LinkColor = System.Drawing.Color.White;
            this.lnkLogout.Location = new System.Drawing.Point(43, 494);
            this.lnkLogout.Name = "lnkLogout";
            this.lnkLogout.Size = new System.Drawing.Size(59, 20);
            this.lnkLogout.TabIndex = 5;
            this.lnkLogout.TabStop = true;
            this.lnkLogout.Text = "Logout";
            this.lnkLogout.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lnkLogout_LinkClicked);
            // 
            // frmUserOrder
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.DarkSlateBlue;
            this.ClientSize = new System.Drawing.Size(918, 583);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.btnClose);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmUserOrder";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmItem";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvItems)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuFormControlBox btnClose;
        private Bunifu.UI.WinForms.BunifuLabel lblPlacOrder;
        private Bunifu.UI.WinForms.BunifuFormDrag bunifuFormDrag1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.ComboBox cmbCategory;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvItems;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrderNum;
        private Bunifu.UI.WinForms.BunifuTextBox txtSellerName;
        private Bunifu.UI.WinForms.BunifuLabel lblOrdAmount;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddToCart;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuLabel lblYourOrder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPlaceOrder;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private System.Windows.Forms.LinkLabel lnkLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnItems;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUsers;
    }
}